export const actions = {
	INIT_APP: 'INIT_APP',
	SET_CURRENT_ROUTE: 'SET_CURRENT_ROUTE',

	ADD_POST: 'ADD_POST',

	SEND_MESSAGE: 'SEND_MESSAGE',

	FOLLOW_USER: 'FOLLOW_USER',
	UNFOLLOW_USER: 'UNFOLLOW_USER',
	SET_USERS: 'SET_USERS',
	SET_CURRENT_USERS_PAGE: 'SET_CURRENT_USERS_PAGE',
	TOGGLE_IS_FETCHING: 'TOGGLE_IS_FETCHING',
	TOGGLE_FOLLOWING: 'TOGGLE_FOLLOWING',

	SET_USER_PROFILE: 'SET_USER_PROFILE',
	SET_STATUS: 'SET_STATUS',

	SET_AUTH_DATA: 'SET_AUTH_DATA',
	SET_IS_AUTH: 'SET_IS_AUTH',
	TOGGLE_CHECKING_AUTH: 'TOGGLE_CHECKING_AUTH',
	STOP_SUBMIT: 'STOP_SUBMIT'
};