export const actions = {
	ADD_POST: 'ADD_POST',
	HANDLE_NEW_POST_CHANGE: 'HANDLE_NEW_POST_CHANGE',
	SEND_MESSAGE: 'SEND_MESSAGE',
	HANDLE_NEW_MESSAGE_CHANGE: 'HANDLE_NEW_MESSAGE_CHANGE',
	FOLLOW_USER: 'FOLLOW_USER',
	UNFOLLOW_USER: 'UNFOLLOW_USER',
	SET_USERS: 'SET_USERS',
	SET_CURRENT_USERS_PAGE: 'SET_CURRENT_USERS_PAGE'
};